"""add acronym column

Revision ID: 469c394f9b3b
Revises: 851ae3014ba1
Create Date: 2026-04-02 11:36:45.630872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469c394f9b3b'
down_revision: Union[str, None] = '851ae3014ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('acronym', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'acronym')
    # ### end Alembic commands ###
