"""make geometry required

Revision ID: 90a269e86bfc
Revises: d089ecabc3fd
Create Date: 2026-04-02 10:26:42.408596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '90a269e86bfc'
down_revision: Union[str, None] = 'd089ecabc3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'geometry',
                    existing_type=geoalchemy2.types.Geometry(
                        geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
                    nullable=False)
    op.add_column('universities', sa.Column('geometry', geoalchemy2.types.Geometry(
        geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_universities_geometry ON universities USING gist (geometry)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_universities_geometry',
                  table_name='universities', postgresql_using='gist')
    op.drop_column('universities', 'geometry')
    op.alter_column('submissions', 'geometry',
                    existing_type=geoalchemy2.types.Geometry(
                        geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
                    nullable=True)
    # ### end Alembic commands ###
