"""Add submission

Revision ID: a20b59931ce4
Revises: fdfab5b59ac6
Create Date: 2026-03-30 15:17:14.534703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a20b59931ce4'
down_revision: Union[str, None] = 'fdfab5b59ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
                    sa.Column('institution_name', sa.String(), nullable=False),
                    sa.Column('country', sa.String(), nullable=False),
                    sa.Column('city', sa.String(), nullable=False),
                    sa.Column('address', sa.Text(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.Column('chapter_name', sa.String(), nullable=False),
                    sa.Column('percentage_osm_coverage',
                              sa.Float(), nullable=False),
                    sa.Column('contributor_name', sa.String(), nullable=False),
                    sa.Column('contributor_email',
                              sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('role_in_chapter', sa.String(), nullable=True),
                    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326,
                                                                     dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
                    sa.Column('picture_url', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_submissions_geometry
        ON submissions USING gist (geometry)
    """)
    op.create_index(op.f('ix_submissions_id'),
                    'submissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index('idx_submissions_geometry',
                  table_name='submissions', postgresql_using='gist')
    op.drop_table('submissions')
    # ### end Alembic commands ###
