"""geometry not required

Revision ID: d089ecabc3fd
Revises: 0c20e00fe429
Create Date: 2026-03-30 21:06:43.710581

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd089ecabc3fd'
down_revision: Union[str, None] = '0c20e00fe429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'geometry',
                    existing_type=geoalchemy2.types.Geometry(
                        geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'geometry',
                    existing_type=geoalchemy2.types.Geometry(
                        geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
                    nullable=False)
    # ### end Alembic commands ###
